---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make manifests
    - make generate
    - go fmt ./...
    - go vet ./...

builds:
  - id: "weka-operator"
    env:
      - CGO_ENABLED=0
    targets:
      - "darwin_arm64"
      - "linux_amd64"
    main: "./cmd/manager"
  - id: "device-plugin"
    env:
      - CGO_ENABLED=0
    targets:
      - "linux_amd64"
      - "darwin_arm64"
    main: "./cmd/device-plugin"

dockers:
  - image_templates:
      - "quay.io/weka.io/weka-operator:{{ .Tag }}"
      - "quay.io/weka.io/weka-operator:{{ .Major }}"
      - "quay.io/weka.io/weka-operator:{{ .Major }}.{{ .Minor }}"
      - "quay.io/weka.io/weka-operator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "quay.io/weka.io/weka-operator:latest"

    dockerfile: "Dockerfile.release"
    build_flag_templates:
      - "--target=manager"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
