---
version: 1

before:
  hooks:
    - go generate ./...
    - go mod tidy
    - make manifests
    - make generate
    - go fmt ./...
    - go vet ./...
#    - make test

builds:
  - id: "weka-operator"
    env:
      - CGO_ENABLED=0
    targets:
      - "darwin_arm64"
      - "linux_amd64"
    binary: "manager"
    main: "./cmd/manager"

#  - id: node-labeller
#    env:
#      - CGO_ENABLED=0
#    targets:
#      - "darwin_arm64"
#      - "linux_amd64"
#    main: "./cmd/node-labeller"
#    binary: "node-labeller"

dockers:
  - image_templates:
      #      - "{{ .Env.REGISTRY_ENDPOINT }}/weka-operator:{{ .Tag }}-{{ .ShortCommit }}"
      #            - "{{ .Env.REGISTRY_ENDPOINT }}/weka-operator:latest"
      - "{{ .Env.REGISTRY_ENDPOINT }}/weka-operator:{{ .Env.VERSION }}"

    dockerfile: "Dockerfile.release"
    use: buildx

    build_flag_templates:
      - "--target=manager"

#  - image_templates:
#      - "quay.io/weka.io/weka-operator-node-labeller:{{ .Tag }}-{{ .ShortCommit }}"
#      - "quay.io/weka.io/weka-operator-node-labeller:latest"
#      - "quay.io/weka.io/weka-operator-node-labeller:latest"
#      - "{{ .Env.REGISTRY_ENDPOINT }}/weka-operator-node-labeller:{IMG_TAG}"
#    dockerfile: "Dockerfile.release"
#    use: "buildx"
#    build_flag_templates:
#      - "--target=node-labeller"

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
