---
version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make manifests
    - make generate
    - go fmt ./...
    - go vet ./...
    - make test

builds:
  - id: "weka-operator"
    env:
      - CGO_ENABLED=0
    targets:
      - "darwin_arm64"
      - "linux_amd64"
    main: "./cmd/manager"
    binary: "manager"
  - id: "device-plugin"
    env:
      - CGO_ENABLED=0
    targets:
      - "darwin_arm64"
      - "linux_amd64"
    main: "./cmd/device-plugin"
    binary: "device-plugin"
  - id: node-labeller
    env:
      - CGO_ENABLED=0
    targets:
      - "darwin_arm64"
      - "linux_amd64"
    main: "./cmd/node-labeller"
    binary: "node-labeller"

dockers:
  - image_templates:
      - "quay.io/weka.io/weka-operator:{{ .Tag }}-{{ .ShortCommit }}"
      - "quay.io/weka.io/weka-operator:latest"

    dockerfile: "Dockerfile.release"

    build_flag_templates:
      - "--target=manager"

  - image_templates:
      - "quay.io/weka.io/weka-operator-device-plugin:{{ .Tag }}-{{ .ShortCommit }}"
      - "quay.io/weka.io/weka-operator-device-plugin:latest"
    dockerfile: "Dockerfile.release"
    build_flag_templates:
      - "--target=device-plugin"

  - image_templates:
      - "quay.io/weka.io/weka-operator-node-labeller:{{ .Tag }}-{{ .ShortCommit }}"
      - "quay.io/weka.io/weka-operator-node-labeller:latest"
    dockerfile: "Dockerfile.release"
    build_flag_templates:
      - "--target=node-labeller"

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
