#!/usr/bin/env bash
set -euo pipefail

ENGINE_NAME="dagger-engine-v0.19.10" # is it in use by default? not sure, but keeping for reference
ENGINE_IMAGE="registry.dagger.io/engine:v0.19.10"

# supressing ugly logs/unsetting OTEL
unset OTEL_EXPORTER_OTLP_ENDPOINT ANTHROPIC_API_KEY
export DAGGER_NO_NAG=1

exec dagger "$@"

