FROM scratch as builder

USER 65532:65532

FROM builder as manager
COPY manager /manager

FROM builder as device-plugin
COPY device-plugin /device-plugin

FROM builder as node-labeller
COPY node-labeller /node-labeller
