---
# https://taskfile.dev
version: "3"

includes:
  build: ./taskfiles/build
  docker: ./taskfiles/docker
  release: ./taskfiles/release

tasks:
  default:
    cmds:
      - task: build:default

  release:
    cmds:
      - task: build
      - task: release:default

  test:
    cmds:
      - go test -v ./internal/... ./util/... -coverprofile cover.out
