---
# https://taskfile.dev
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps:
      - build

  build:
    cmds:
      - go build -o ./dist/manager ./cmd/manager
    deps:
      - generate

  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v ./internal/... ./util/... -coverprofile cover.out
