//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSNetwork) DeepCopyInto(out *AWSNetwork) {
	*out = *in
	if in.DeviceSlots != nil {
		in, out := &in.DeviceSlots, &out.DeviceSlots
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSNetwork.
func (in *AWSNetwork) DeepCopy() *AWSNetwork {
	if in == nil {
		return nil
	}
	out := new(AWSNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalMemory) DeepCopyInto(out *AdditionalMemory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalMemory.
func (in *AdditionalMemory) DeepCopy() *AdditionalMemory {
	if in == nil {
		return nil
	}
	out := new(AdditionalMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDrivesPayload) DeepCopyInto(out *BlockDrivesPayload) {
	*out = *in
	if in.SerialIDs != nil {
		in, out := &in.SerialIDs, &out.SerialIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDrivesPayload.
func (in *BlockDrivesPayload) DeepCopy() *BlockDrivesPayload {
	if in == nil {
		return nil
	}
	out := new(BlockDrivesPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientContainerSpec) DeepCopyInto(out *ClientContainerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientContainerSpec.
func (in *ClientContainerSpec) DeepCopy() *ClientContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ClientContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMetrics) DeepCopyInto(out *ClusterMetrics) {
	*out = *in
	in.Containers.DeepCopyInto(&out.Containers)
	out.IoStats = in.IoStats
	in.Drives.DeepCopyInto(&out.Drives)
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMetrics.
func (in *ClusterMetrics) DeepCopy() *ClusterMetrics {
	if in == nil {
		return nil
	}
	out := new(ClusterMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPorts) DeepCopyInto(out *ClusterPorts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPorts.
func (in *ClusterPorts) DeepCopy() *ClusterPorts {
	if in == nil {
		return nil
	}
	out := new(ClusterPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPrinterColumns) DeepCopyInto(out *ClusterPrinterColumns) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPrinterColumns.
func (in *ClusterPrinterColumns) DeepCopy() *ClusterPrinterColumns {
	if in == nil {
		return nil
	}
	out := new(ClusterPrinterColumns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerAllocations) DeepCopyInto(out *ContainerAllocations) {
	*out = *in
	if in.Drives != nil {
		in, out := &in.Drives, &out.Drives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EthSlots != nil {
		in, out := &in.EthSlots, &out.EthSlots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailureDomain != nil {
		in, out := &in.FailureDomain, &out.FailureDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerAllocations.
func (in *ContainerAllocations) DeepCopy() *ContainerAllocations {
	if in == nil {
		return nil
	}
	out := new(ContainerAllocations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerMetrics) DeepCopyInto(out *ContainerMetrics) {
	*out = *in
	out.Containers = in.Containers
	out.Processes = in.Processes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerMetrics.
func (in *ContainerMetrics) DeepCopy() *ContainerMetrics {
	if in == nil {
		return nil
	}
	out := new(ContainerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerPrinterColumns) DeepCopyInto(out *ContainerPrinterColumns) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerPrinterColumns.
func (in *ContainerPrinterColumns) DeepCopy() *ContainerPrinterColumns {
	if in == nil {
		return nil
	}
	out := new(ContainerPrinterColumns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainersMetrics) DeepCopyInto(out *ContainersMetrics) {
	*out = *in
	out.Drive = in.Drive
	out.Compute = in.Compute
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ContainerMetrics)
		**out = **in
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = new(ContainerMetrics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainersMetrics.
func (in *ContainersMetrics) DeepCopy() *ContainersMetrics {
	if in == nil {
		return nil
	}
	out := new(ContainersMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverDrivesPayload) DeepCopyInto(out *DiscoverDrivesPayload) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverDrivesPayload.
func (in *DiscoverDrivesPayload) DeepCopy() *DiscoverDrivesPayload {
	if in == nil {
		return nil
	}
	out := new(DiscoverDrivesPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveClaim) DeepCopyInto(out *DriveClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveClaim.
func (in *DriveClaim) DeepCopy() *DriveClaim {
	if in == nil {
		return nil
	}
	out := new(DriveClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriveClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveClaimList) DeepCopyInto(out *DriveClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriveClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveClaimList.
func (in *DriveClaimList) DeepCopy() *DriveClaimList {
	if in == nil {
		return nil
	}
	out := new(DriveClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriveClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveClaimSpec) DeepCopyInto(out *DriveClaimSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveClaimSpec.
func (in *DriveClaimSpec) DeepCopy() *DriveClaimSpec {
	if in == nil {
		return nil
	}
	out := new(DriveClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveClaimStatus) DeepCopyInto(out *DriveClaimStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveClaimStatus.
func (in *DriveClaimStatus) DeepCopy() *DriveClaimStatus {
	if in == nil {
		return nil
	}
	out := new(DriveClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveFailures) DeepCopyInto(out *DriveFailures) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveFailures.
func (in *DriveFailures) DeepCopy() *DriveFailures {
	if in == nil {
		return nil
	}
	out := new(DriveFailures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriveMetrics) DeepCopyInto(out *DriveMetrics) {
	*out = *in
	out.DriveCounters = in.DriveCounters
	if in.DriveFailures != nil {
		in, out := &in.DriveFailures, &out.DriveFailures
		*out = make([]DriveFailures, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriveMetrics.
func (in *DriveMetrics) DeepCopy() *DriveMetrics {
	if in == nil {
		return nil
	}
	out := new(DriveMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverSpec) DeepCopyInto(out *DriverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverSpec.
func (in *DriverSpec) DeepCopy() *DriverSpec {
	if in == nil {
		return nil
	}
	out := new(DriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnsureNICsPayload) DeepCopyInto(out *EnsureNICsPayload) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnsureNICsPayload.
func (in *EnsureNICsPayload) DeepCopy() *EnsureNICsPayload {
	if in == nil {
		return nil
	}
	out := new(EnsureNICsPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityStatefulNum) DeepCopyInto(out *EntityStatefulNum) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityStatefulNum.
func (in *EntityStatefulNum) DeepCopy() *EntityStatefulNum {
	if in == nil {
		return nil
	}
	out := new(EntityStatefulNum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForceResignDrivesPayload) DeepCopyInto(out *ForceResignDrivesPayload) {
	*out = *in
	if in.DeviceSerials != nil {
		in, out := &in.DeviceSerials, &out.DeviceSerials
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DevicePaths != nil {
		in, out := &in.DevicePaths, &out.DevicePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForceResignDrivesPayload.
func (in *ForceResignDrivesPayload) DeepCopy() *ForceResignDrivesPayload {
	if in == nil {
		return nil
	}
	out := new(ForceResignDrivesPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instructions) DeepCopyInto(out *Instructions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instructions.
func (in *Instructions) DeepCopy() *Instructions {
	if in == nil {
		return nil
	}
	out := new(Instructions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoStats) DeepCopyInto(out *IoStats) {
	*out = *in
	out.Throughput = in.Throughput
	out.Iops = in.Iops
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoStats.
func (in *IoStats) DeepCopy() *IoStats {
	if in == nil {
		return nil
	}
	out := new(IoStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperatorPayload) DeepCopyInto(out *ManualOperatorPayload) {
	*out = *in
	if in.SignDrives != nil {
		in, out := &in.SignDrives, &out.SignDrives
		*out = new(SignDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDrives != nil {
		in, out := &in.BlockDrives, &out.BlockDrives
		*out = new(BlockDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoverDrives != nil {
		in, out := &in.DiscoverDrives, &out.DiscoverDrives
		*out = new(DiscoverDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.EnsureNICs != nil {
		in, out := &in.EnsureNICs, &out.EnsureNICs
		*out = new(EnsureNICsPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.ForceResignDrives != nil {
		in, out := &in.ForceResignDrives, &out.ForceResignDrives
		*out = new(ForceResignDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteTracesSessionConfig != nil {
		in, out := &in.RemoteTracesSessionConfig, &out.RemoteTracesSessionConfig
		*out = new(RemoteTracesSessionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperatorPayload.
func (in *ManualOperatorPayload) DeepCopy() *ManualOperatorPayload {
	if in == nil {
		return nil
	}
	out := new(ManualOperatorPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinMaxAvgPercent) DeepCopyInto(out *MinMaxAvgPercent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinMaxAvgPercent.
func (in *MinMaxAvgPercent) DeepCopy() *MinMaxAvgPercent {
	if in == nil {
		return nil
	}
	out := new(MinMaxAvgPercent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	if in.EthDevices != nil {
		in, out := &in.EthDevices, &out.EthDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AWS.DeepCopyInto(&out.AWS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSelector) DeepCopyInto(out *NetworkSelector) {
	*out = *in
	if in.EthSlots != nil {
		in, out := &in.EthSlots, &out.EthSlots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EthDevices != nil {
		in, out := &in.EthDevices, &out.EthDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSelector.
func (in *NetworkSelector) DeepCopy() *NetworkSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDevices) DeepCopyInto(out *PCIDevices) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDevices.
func (in *PCIDevices) DeepCopy() *PCIDevices {
	if in == nil {
		return nil
	}
	out := new(PCIDevices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConfiguration) DeepCopyInto(out *PodConfiguration) {
	*out = *in
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoleTopologySpreadConstraints != nil {
		in, out := &in.RoleTopologySpreadConstraints, &out.RoleTopologySpreadConstraints
		*out = new(RoleTopologySpreadConstraints)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleAffinity != nil {
		in, out := &in.RoleAffinity, &out.RoleAffinity
		*out = new(RoleAffinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConfiguration.
func (in *PodConfiguration) DeepCopy() *PodConfiguration {
	if in == nil {
		return nil
	}
	out := new(PodConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPayload) DeepCopyInto(out *PolicyPayload) {
	*out = *in
	if in.SignDrives != nil {
		in, out := &in.SignDrives, &out.SignDrives
		*out = new(SignDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulingConfig != nil {
		in, out := &in.SchedulingConfig, &out.SchedulingConfig
		*out = new(SchedulingConfigPayload)
		**out = **in
	}
	if in.DiscoverDrives != nil {
		in, out := &in.DiscoverDrives, &out.DiscoverDrives
		*out = new(DiscoverDrivesPayload)
		(*in).DeepCopyInto(*out)
	}
	if in.WaitForPolicies != nil {
		in, out := &in.WaitForPolicies, &out.WaitForPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPayload.
func (in *PolicyPayload) DeepCopy() *PolicyPayload {
	if in == nil {
		return nil
	}
	out := new(PolicyPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRange.
func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTracesSessionConfig) DeepCopyInto(out *RemoteTracesSessionConfig) {
	*out = *in
	out.Cluster = in.Cluster
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Duration = in.Duration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTracesSessionConfig.
func (in *RemoteTracesSessionConfig) DeepCopy() *RemoteTracesSessionConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteTracesSessionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleAffinity) DeepCopyInto(out *RoleAffinity) {
	*out = *in
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Drive != nil {
		in, out := &in.Drive, &out.Drive
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleAffinity.
func (in *RoleAffinity) DeepCopy() *RoleAffinity {
	if in == nil {
		return nil
	}
	out := new(RoleAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleNodeSelector) DeepCopyInto(out *RoleNodeSelector) {
	*out = *in
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Drive != nil {
		in, out := &in.Drive, &out.Drive
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleNodeSelector.
func (in *RoleNodeSelector) DeepCopy() *RoleNodeSelector {
	if in == nil {
		return nil
	}
	out := new(RoleNodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleTopologySpreadConstraints) DeepCopyInto(out *RoleTopologySpreadConstraints) {
	*out = *in
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Drive != nil {
		in, out := &in.Drive, &out.Drive
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nfs != nil {
		in, out := &in.Nfs, &out.Nfs
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleTopologySpreadConstraints.
func (in *RoleTopologySpreadConstraints) DeepCopy() *RoleTopologySpreadConstraints {
	if in == nil {
		return nil
	}
	out := new(RoleTopologySpreadConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Params) DeepCopyInto(out *S3Params) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Params.
func (in *S3Params) DeepCopy() *S3Params {
	if in == nil {
		return nil
	}
	out := new(S3Params)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConfigPayload) DeepCopyInto(out *SchedulingConfigPayload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConfigPayload.
func (in *SchedulingConfigPayload) DeepCopy() *SchedulingConfigPayload {
	if in == nil {
		return nil
	}
	out := new(SchedulingConfigPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignDrivesPayload) DeepCopyInto(out *SignDrivesPayload) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DevicePaths != nil {
		in, out := &in.DevicePaths, &out.DevicePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCIDevices != nil {
		in, out := &in.PCIDevices, &out.PCIDevices
		*out = new(PCIDevices)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignDrivesPayload.
func (in *SignDrivesPayload) DeepCopy() *SignDrivesPayload {
	if in == nil {
		return nil
	}
	out := new(SignDrivesPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusIops) DeepCopyInto(out *StatusIops) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusIops.
func (in *StatusIops) DeepCopy() *StatusIops {
	if in == nil {
		return nil
	}
	out := new(StatusIops)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusThroughput) DeepCopyInto(out *StatusThroughput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusThroughput.
func (in *StatusThroughput) DeepCopy() *StatusThroughput {
	if in == nil {
		return nil
	}
	out := new(StatusThroughput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tombstone) DeepCopyInto(out *Tombstone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tombstone.
func (in *Tombstone) DeepCopy() *Tombstone {
	if in == nil {
		return nil
	}
	out := new(Tombstone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tombstone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TombstoneList) DeepCopyInto(out *TombstoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tombstone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TombstoneList.
func (in *TombstoneList) DeepCopy() *TombstoneList {
	if in == nil {
		return nil
	}
	out := new(TombstoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TombstoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TombstoneSpec) DeepCopyInto(out *TombstoneSpec) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TombstoneSpec.
func (in *TombstoneSpec) DeepCopy() *TombstoneSpec {
	if in == nil {
		return nil
	}
	out := new(TombstoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TombstoneStatus) DeepCopyInto(out *TombstoneStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TombstoneStatus.
func (in *TombstoneStatus) DeepCopy() *TombstoneStatus {
	if in == nil {
		return nil
	}
	out := new(TombstoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracesConfiguration) DeepCopyInto(out *TracesConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracesConfiguration.
func (in *TracesConfiguration) DeepCopy() *TracesConfiguration {
	if in == nil {
		return nil
	}
	out := new(TracesConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePolicy) DeepCopyInto(out *UpgradePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePolicy.
func (in *UpgradePolicy) DeepCopy() *UpgradePolicy {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClient) DeepCopyInto(out *WekaClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClient.
func (in *WekaClient) DeepCopy() *WekaClient {
	if in == nil {
		return nil
	}
	out := new(WekaClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClientList) DeepCopyInto(out *WekaClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WekaClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClientList.
func (in *WekaClientList) DeepCopy() *WekaClientList {
	if in == nil {
		return nil
	}
	out := new(WekaClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClientSpec) DeepCopyInto(out *WekaClientSpec) {
	*out = *in
	if in.PortRange != nil {
		in, out := &in.PortRange, &out.PortRange
		*out = new(PortRange)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.NetworkSelector.DeepCopyInto(&out.NetworkSelector)
	if in.JoinIps != nil {
		in, out := &in.JoinIps, &out.JoinIps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TargetCluster = in.TargetCluster
	if in.CoreIds != nil {
		in, out := &in.CoreIds, &out.CoreIds
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.TracesConfiguration != nil {
		in, out := &in.TracesConfiguration, &out.TracesConfiguration
		*out = new(TracesConfiguration)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RawTolerations != nil {
		in, out := &in.RawTolerations, &out.RawTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.WekaHomeConfig = in.WekaHomeConfig
	if in.WekaHome != nil {
		in, out := &in.WekaHome, &out.WekaHome
		*out = new(WekahomeClientConfig)
		**out = **in
	}
	out.UpgradePolicy = in.UpgradePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClientSpec.
func (in *WekaClientSpec) DeepCopy() *WekaClientSpec {
	if in == nil {
		return nil
	}
	out := new(WekaClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClientStatus) DeepCopyInto(out *WekaClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClientStatus.
func (in *WekaClientStatus) DeepCopy() *WekaClientStatus {
	if in == nil {
		return nil
	}
	out := new(WekaClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaCluster) DeepCopyInto(out *WekaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaCluster.
func (in *WekaCluster) DeepCopy() *WekaCluster {
	if in == nil {
		return nil
	}
	out := new(WekaCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClusterList) DeepCopyInto(out *WekaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WekaCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClusterList.
func (in *WekaClusterList) DeepCopy() *WekaClusterList {
	if in == nil {
		return nil
	}
	out := new(WekaClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClusterSpec) DeepCopyInto(out *WekaClusterSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.RoleNodeSelector.DeepCopyInto(&out.RoleNodeSelector)
	if in.FailureDomainLabel != nil {
		in, out := &in.FailureDomainLabel, &out.FailureDomainLabel
		*out = new(string)
		**out = **in
	}
	if in.PodConfig != nil {
		in, out := &in.PodConfig, &out.PodConfig
		*out = new(PodConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.TracesConfiguration != nil {
		in, out := &in.TracesConfiguration, &out.TracesConfiguration
		*out = new(TracesConfiguration)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RawTolerations != nil {
		in, out := &in.RawTolerations, &out.RawTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WekaHome != nil {
		in, out := &in.WekaHome, &out.WekaHome
		*out = new(WekaHomeConfig)
		(*in).DeepCopyInto(*out)
	}
	out.AdditionalMemory = in.AdditionalMemory
	out.Ports = in.Ports
	if in.ExpandEndpoints != nil {
		in, out := &in.ExpandEndpoints, &out.ExpandEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = new(WekaConfig)
		(*in).DeepCopyInto(*out)
	}
	in.NetworkSelector.DeepCopyInto(&out.NetworkSelector)
	if in.LeadershipSize != nil {
		in, out := &in.LeadershipSize, &out.LeadershipSize
		*out = new(int)
		**out = **in
	}
	if in.BucketRaftSize != nil {
		in, out := &in.BucketRaftSize, &out.BucketRaftSize
		*out = new(int)
		**out = **in
	}
	out.GracefulDestroyDuration = in.GracefulDestroyDuration
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(WekaClusterSpecOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClusterSpec.
func (in *WekaClusterSpec) DeepCopy() *WekaClusterSpec {
	if in == nil {
		return nil
	}
	out := new(WekaClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClusterSpecOverrides) DeepCopyInto(out *WekaClusterSpecOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClusterSpecOverrides.
func (in *WekaClusterSpecOverrides) DeepCopy() *WekaClusterSpecOverrides {
	if in == nil {
		return nil
	}
	out := new(WekaClusterSpecOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaClusterStatus) DeepCopyInto(out *WekaClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Ports = in.Ports
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(ClusterMetrics)
		(*in).DeepCopyInto(*out)
	}
	out.PrinterColumns = in.PrinterColumns
	if in.Timestamps != nil {
		in, out := &in.Timestamps, &out.Timestamps
		*out = make(map[string]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaClusterStatus.
func (in *WekaClusterStatus) DeepCopy() *WekaClusterStatus {
	if in == nil {
		return nil
	}
	out := new(WekaClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaConfig) DeepCopyInto(out *WekaConfig) {
	*out = *in
	if in.ComputeContainers != nil {
		in, out := &in.ComputeContainers, &out.ComputeContainers
		*out = new(int)
		**out = **in
	}
	if in.DriveContainers != nil {
		in, out := &in.DriveContainers, &out.DriveContainers
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaConfig.
func (in *WekaConfig) DeepCopy() *WekaConfig {
	if in == nil {
		return nil
	}
	out := new(WekaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainer) DeepCopyInto(out *WekaContainer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainer.
func (in *WekaContainer) DeepCopy() *WekaContainer {
	if in == nil {
		return nil
	}
	out := new(WekaContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaContainer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerDetails) DeepCopyInto(out *WekaContainerDetails) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerDetails.
func (in *WekaContainerDetails) DeepCopy() *WekaContainerDetails {
	if in == nil {
		return nil
	}
	out := new(WekaContainerDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerList) DeepCopyInto(out *WekaContainerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WekaContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerList.
func (in *WekaContainerList) DeepCopy() *WekaContainerList {
	if in == nil {
		return nil
	}
	out := new(WekaContainerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaContainerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerMetrics) DeepCopyInto(out *WekaContainerMetrics) {
	*out = *in
	out.Processes = in.Processes
	in.Drives.DeepCopyInto(&out.Drives)
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerMetrics.
func (in *WekaContainerMetrics) DeepCopy() *WekaContainerMetrics {
	if in == nil {
		return nil
	}
	out := new(WekaContainerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerSpec) DeepCopyInto(out *WekaContainerSpec) {
	*out = *in
	if in.FailureDomainLabel != nil {
		in, out := &in.FailureDomainLabel, &out.FailureDomainLabel
		*out = new(string)
		**out = **in
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PortRange != nil {
		in, out := &in.PortRange, &out.PortRange
		*out = new(PortRange)
		**out = **in
	}
	if in.CoreIds != nil {
		in, out := &in.CoreIds, &out.CoreIds
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	in.Network.DeepCopyInto(&out.Network)
	in.WekaSecretRef.DeepCopyInto(&out.WekaSecretRef)
	if in.JoinIps != nil {
		in, out := &in.JoinIps, &out.JoinIps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TracesConfiguration != nil {
		in, out := &in.TracesConfiguration, &out.TracesConfiguration
		*out = new(TracesConfiguration)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalSecrets != nil {
		in, out := &in.AdditionalSecrets, &out.AdditionalSecrets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = new(Instructions)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(WekaContainerSpecOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerSpec.
func (in *WekaContainerSpec) DeepCopy() *WekaContainerSpec {
	if in == nil {
		return nil
	}
	out := new(WekaContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerSpecOverrides) DeepCopyInto(out *WekaContainerSpecOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerSpecOverrides.
func (in *WekaContainerSpecOverrides) DeepCopy() *WekaContainerSpecOverrides {
	if in == nil {
		return nil
	}
	out := new(WekaContainerSpecOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaContainerStatus) DeepCopyInto(out *WekaContainerStatus) {
	*out = *in
	if in.ClusterContainerID != nil {
		in, out := &in.ClusterContainerID, &out.ClusterContainerID
		*out = new(int)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExecutionResult != nil {
		in, out := &in.ExecutionResult, &out.ExecutionResult
		*out = new(string)
		**out = **in
	}
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = new(ContainerAllocations)
		(*in).DeepCopyInto(*out)
	}
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(WekaContainerMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.PrinterColumns != nil {
		in, out := &in.PrinterColumns, &out.PrinterColumns
		*out = new(ContainerPrinterColumns)
		**out = **in
	}
	if in.Timestamps != nil {
		in, out := &in.Timestamps, &out.Timestamps
		*out = make(map[string]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaContainerStatus.
func (in *WekaContainerStatus) DeepCopy() *WekaContainerStatus {
	if in == nil {
		return nil
	}
	out := new(WekaContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaHomeConfig) DeepCopyInto(out *WekaHomeConfig) {
	*out = *in
	if in.EnableStats != nil {
		in, out := &in.EnableStats, &out.EnableStats
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaHomeConfig.
func (in *WekaHomeConfig) DeepCopy() *WekaHomeConfig {
	if in == nil {
		return nil
	}
	out := new(WekaHomeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaManualOperation) DeepCopyInto(out *WekaManualOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaManualOperation.
func (in *WekaManualOperation) DeepCopy() *WekaManualOperation {
	if in == nil {
		return nil
	}
	out := new(WekaManualOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaManualOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaManualOperationList) DeepCopyInto(out *WekaManualOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WekaManualOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaManualOperationList.
func (in *WekaManualOperationList) DeepCopy() *WekaManualOperationList {
	if in == nil {
		return nil
	}
	out := new(WekaManualOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaManualOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaManualOperationSpec) DeepCopyInto(out *WekaManualOperationSpec) {
	*out = *in
	in.Payload.DeepCopyInto(&out.Payload)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaManualOperationSpec.
func (in *WekaManualOperationSpec) DeepCopy() *WekaManualOperationSpec {
	if in == nil {
		return nil
	}
	out := new(WekaManualOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaManualOperationStatus) DeepCopyInto(out *WekaManualOperationStatus) {
	*out = *in
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaManualOperationStatus.
func (in *WekaManualOperationStatus) DeepCopy() *WekaManualOperationStatus {
	if in == nil {
		return nil
	}
	out := new(WekaManualOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaPolicy) DeepCopyInto(out *WekaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaPolicy.
func (in *WekaPolicy) DeepCopy() *WekaPolicy {
	if in == nil {
		return nil
	}
	out := new(WekaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaPolicyList) DeepCopyInto(out *WekaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WekaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaPolicyList.
func (in *WekaPolicyList) DeepCopy() *WekaPolicyList {
	if in == nil {
		return nil
	}
	out := new(WekaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WekaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaPolicySpec) DeepCopyInto(out *WekaPolicySpec) {
	*out = *in
	in.Payload.DeepCopyInto(&out.Payload)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaPolicySpec.
func (in *WekaPolicySpec) DeepCopy() *WekaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WekaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekaPolicyStatus) DeepCopyInto(out *WekaPolicyStatus) {
	*out = *in
	in.LastRunTime.DeepCopyInto(&out.LastRunTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekaPolicyStatus.
func (in *WekaPolicyStatus) DeepCopy() *WekaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WekaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WekahomeClientConfig) DeepCopyInto(out *WekahomeClientConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WekahomeClientConfig.
func (in *WekahomeClientConfig) DeepCopy() *WekahomeClientConfig {
	if in == nil {
		return nil
	}
	out := new(WekahomeClientConfig)
	in.DeepCopyInto(out)
	return out
}
