#!/usr/bin/env python3
"""Split crd-ref-docs output into per-CRD files with hierarchical navigation.

Reads docs/index.md (generated by crd-ref-docs), groups types by their root CRD
using the _Appears in:_ markers, writes separate docs per CRD, and updates
mkdocs.yml navigation.
"""

import json
import re
import os
from collections import defaultdict, deque

DOCS_DIR = "docs"
INPUT_FILE = os.path.join(DOCS_DIR, "index.md")
MKDOCS_FILE = "mkdocs.yml"

# Navigation grouping: root CRD name -> (group label, display order)
NAV_GROUPS = {
    "Cluster Resources": ["WekaCluster", "WekaClient", "WekaContainer"],
    "Utility Resources": ["WekaManualOperation", "WekaPolicy"],
}

# Root CRD types that should always be treated as independent roots,
# even if they share sub-types with other roots via _Appears in:_ links.
ROOT_CRDS = {"WekaCluster", "WekaClient", "WekaContainer"}


def parse_sections(content):
    """Parse markdown into type sections. Returns dict of type_name -> body."""
    sections = {}
    parts = re.split(r"^(#### \w+)", content, flags=re.MULTILINE)
    # parts: [preamble, "#### TypeA", bodyA, "#### TypeB", bodyB, ...]
    for i in range(1, len(parts), 2):
        type_name = parts[i].replace("#### ", "")
        body = parts[i + 1] if i + 1 < len(parts) else ""
        sections[type_name] = body
    return sections


def extract_parents(body):
    """Extract parent type names from _Appears in:_ block."""
    parents = []
    in_appears = False
    for line in body.splitlines():
        if line.strip() == "_Appears in:_":
            in_appears = True
            continue
        if in_appears:
            m = re.match(r"^- \[(\w+)\]\(#\w+\)$", line.strip())
            if m:
                parents.append(m.group(1))
            elif line.strip() and not line.strip().startswith("-"):
                break
    return parents


def build_ownership(sections):
    """Build root -> set of owned types using independent BFS per root.

    Each root CRD gets its own BFS traversal so that shared sub-types
    (e.g. types used by both WekaCluster and WekaClient) appear in all
    relevant pages.  ROOT_CRDS are always treated as independent roots
    and never claimed as children of another root.

    Returns (ownership dict, children_of dict).
    """
    # parent_of[child] = [parent1, parent2, ...]
    parent_of = {}
    children_of = defaultdict(list)
    for type_name, body in sections.items():
        parents = extract_parents(body)
        parent_of[type_name] = parents
        for p in parents:
            children_of[p].append(type_name)

    # Roots: types with no parents, plus any forced ROOT_CRDS
    roots = set(t for t in sections if not parent_of.get(t))
    roots.update(r for r in ROOT_CRDS if r in sections)

    # Independent BFS from each root (types may appear under multiple roots)
    ownership = {}
    for root in sorted(roots):
        owned = set()
        queue = deque([root])
        while queue:
            node = queue.popleft()
            if node in owned:
                continue
            owned.add(node)
            for child in children_of.get(node, []):
                # Don't pull other root CRDs into this tree
                if child not in ROOT_CRDS or child == root:
                    queue.append(child)
        ownership[root] = owned

    return ownership, children_of


def slug_for(root_name):
    return root_name.lower()


def anchor_for(type_name):
    return type_name.lower()


def rewrite_links(body, type_to_files, current_file):
    """Rewrite internal (#anchor) links to (file.md#anchor) for cross-file refs.

    type_to_files maps type_name -> list of filenames containing that type.
    If the type is in the current file, the link stays local (#anchor).
    Otherwise, link to the first file in the list.
    """
    def replacer(m):
        full = m.group(0)
        label = m.group(1)
        anchor = m.group(2)
        # Find which type this anchor belongs to
        target_type = None
        for t in type_to_files:
            if anchor_for(t) == anchor:
                target_type = t
                break
        if not target_type:
            return full
        files = type_to_files[target_type]
        if current_file in files:
            return full  # local anchor
        return f"[{label}]({files[0]}#{anchor})"

    return re.sub(r"\[([^\]]+)\]\(#([a-z0-9]+)\)", replacer, body)


def add_field_anchors(body, type_name):
    """Add HTML anchor IDs to field rows so search can link directly to them.

    Turns ``| `fieldName` _type_ |`` into
    ``| <a id="typename-fieldname"></a>`fieldName` _type_ |``
    """
    slug = type_name.lower()

    def row_replacer(m):
        field = m.group(1)
        anchor_id = f"{slug}-{field.lower()}"
        return m.group(0).replace(
            f"| `{field}`", f'| <a id="{anchor_id}"></a>`{field}`', 1
        )

    return re.sub(r"^\| `(\w+)`", row_replacer, body, flags=re.MULTILINE)


def write_crd_page(root, owned_types, sections, type_to_files, children_of, filename):
    """Write a per-CRD markdown file with hierarchical headings.

    Types are nested under their parents using heading depth:
      # PageTitle  ->  ## Root  ->  ### DirectChild  ->  #### GrandChild ...
    Capped at h6 (######). Types deeper than that stay at h6.
    """
    lines = [f"# {root}\n"]

    # Load kubectl explain path mapping for this root CRD
    explain_paths = {}
    explain_file = os.path.join(DOCS_DIR, "_kubectl_explain.json")
    if os.path.exists(explain_file):
        with open(explain_file) as ef:
            explain_paths = json.load(ef).get(root, {})

    max_depth = 6  # markdown max heading level

    visited = set()

    def render_type(type_name, depth):
        if type_name in visited:
            return
        visited.add(type_name)

        hashes = "#" * min(depth, max_depth)
        body = sections[type_name]
        body = rewrite_links(body, type_to_files, filename)
        body = add_field_anchors(body, type_name)

        # Add kubectl explain hint above the type section
        explain_path = explain_paths.get(type_name)
        explain_hint = ""
        if explain_path:
            explain_hint = (
                f"\n```bash\nkubectl explain {explain_path}\n```\n"
            )

        lines.append(f"{hashes} {type_name}\n{explain_hint}{body}\n")

        # Recurse into children that belong to this page
        children = sorted(
            c for c in children_of.get(type_name, [])
            if c in owned_types and c not in ROOT_CRDS
        )
        for child in children:
            render_type(child, depth + 1)

    render_type(root, 2)

    # Safety net: render any owned types not reachable via the tree
    for t in sorted(owned_types):
        if t not in visited:
            render_type(t, 3)

    path = os.path.join(DOCS_DIR, filename)
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  wrote {path} ({len(owned_types)} types)")


def write_overview(ownership):
    """Write the overview index.md landing page."""
    lines = [
        "# Weka CRD API Reference\n",
        "API reference for the Weka Kubernetes Operator custom resources.\n",
        "## Resource Hierarchy\n",
        "```",
        "WekaCluster",
        "  └── WekaContainer",
        "",
        "WekaClient",
        "  └── WekaContainer",
        "",
        "WekaManualOperation",
        "WekaPolicy",
        "```\n",
        "## Resources\n",
        "| Resource | Types | Description |",
        "| --- | --- | --- |",
    ]

    descriptions = {
        "WekaCluster": "Root resource that defines and manages a Weka cluster",
        "WekaClient": "Client containers that mount to a Weka cluster",
        "WekaContainer": "Individual container instances managed by WekaCluster or WekaClient",
        "WekaManualOperation": "Manual operational actions on the cluster",
        "WekaPolicy": "Policy configuration for cluster behavior",
    }

    for root in sorted(ownership.keys()):
        slug = slug_for(root)
        desc = descriptions.get(root, "")
        count = len(ownership[root])
        lines.append(f"| [{root}]({slug}.md) | {count} | {desc} |")

    lines.append("")

    path = os.path.join(DOCS_DIR, "index.md")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  wrote {path}")


def update_mkdocs_nav(ownership):
    """Update the nav: section in mkdocs.yml."""
    with open(MKDOCS_FILE, "r") as f:
        content = f.read()

    # Build nav entries grouped by category
    nav_lines = ["nav:"]
    nav_lines.append("  - Overview: index.md")

    known_roots = set()
    for group_label, roots in NAV_GROUPS.items():
        group_roots = [r for r in roots if r in ownership]
        if group_roots:
            nav_lines.append(f"  - {group_label}:")
            for root in group_roots:
                nav_lines.append(f"      - {root}: {slug_for(root)}.md")
                known_roots.add(root)

    # Any roots not in NAV_GROUPS go under "Other Resources"
    other = sorted(r for r in ownership if r not in known_roots)
    if other:
        nav_lines.append("  - Other Resources:")
        for root in other:
            nav_lines.append(f"      - {root}: {slug_for(root)}.md")

    nav_block = "\n".join(nav_lines) + "\n"

    # Replace everything from nav: to end of file
    content = re.sub(r"^nav:.*", nav_block, content, flags=re.MULTILINE | re.DOTALL)

    with open(MKDOCS_FILE, "w") as f:
        f.write(content)
    print(f"  updated {MKDOCS_FILE}")


def main():
    with open(INPUT_FILE, "r") as f:
        content = f.read()

    print("Parsing type sections...")
    sections = parse_sections(content)
    print(f"  found {len(sections)} types")

    print("Building ownership tree...")
    ownership, children_of = build_ownership(sections)
    for root, owned in sorted(ownership.items()):
        print(f"  {root}: {len(owned)} types")

    # Map each type to its output filename(s) — types may appear in multiple files
    type_to_files = defaultdict(list)
    for root, owned in sorted(ownership.items()):
        filename = f"{slug_for(root)}.md"
        for t in owned:
            type_to_files[t].append(filename)

    print("Writing per-CRD pages...")
    for root, owned in sorted(ownership.items()):
        filename = f"{slug_for(root)}.md"
        write_crd_page(root, owned, sections, type_to_files, children_of, filename)

    print("Writing overview page...")
    write_overview(ownership)

    print("Updating mkdocs.yml navigation...")
    update_mkdocs_nav(ownership)

    # Clean up temporary file
    explain_file = os.path.join(DOCS_DIR, "_kubectl_explain.json")
    if os.path.exists(explain_file):
        os.remove(explain_file)

    print("Done!")


if __name__ == "__main__":
    main()
