package controllers

import (
	weka "github.com/weka/weka-k8s-api/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
)

// ownerDetailsInput carries the fields an owner object (WekaManualOperation or
// WekaPolicy) contributes to every workload it generates. Named fields keep the two
// optional *string values (Image, ImagePullSecret) from being silently swapped at a
// call site — positional args of the same type were a footgun.
type ownerDetailsInput struct {
	Image              *string
	ImagePullSecret    *string
	Tolerations        []corev1.Toleration
	Labels             map[string]string
	ServiceAccountName string
}

// ownerDetailsFrom builds the WekaOwnerDetails propagated to workloads generated by an
// owner object. WekaManualOperation and WekaPolicy expose the same optional image /
// pull-secret / tolerations / service-account fields (plus object labels), so the mapping
// lives in one place: dropping or mistyping a field here can no longer silently affect only
// one owner kind — which is exactly how ServiceAccountName went missing on the
// manual-operation path before this was centralized.
func ownerDetailsFrom(in ownerDetailsInput) weka.WekaOwnerDetails {
	var image, imagePullSecret string
	if in.Image != nil {
		image = *in.Image
	}
	if in.ImagePullSecret != nil {
		imagePullSecret = *in.ImagePullSecret
	}

	return weka.WekaOwnerDetails{
		Image:              image,
		ImagePullSecret:    imagePullSecret,
		Tolerations:        in.Tolerations,
		Labels:             in.Labels,
		ServiceAccountName: in.ServiceAccountName,
	}
}
