# Drive sharing using containerCapacity with GLOBAL driveTypesRatio default
#
# This example uses containerCapacity WITHOUT an explicit driveTypesRatio.
# The operator automatically applies the global default from Helm values.
# Default: tlc: 1, qlc: 10 (meaning ~9% TLC, ~91% QLC)
#
# To change the global default, set driveTypesRatio in your Helm values.yaml
# To override per-cluster, add explicit driveTypesRatio (see 04-cluster-mixed-drive-types.yaml)
#
# Prerequisites:
# - Drives must be signed for proxy mode (shared: true)
# - Sufficient shared drive capacity available on nodes
# - Physical drives must have type information (TLC/QLC)

apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  # Weka container image
  image: quay.io/weka.io/weka-in-container:WEKA_VERSION
  imagePullSecret: quay-io-secret

  # Driver distribution service
  driversDistService: https://weka-drivers-dist.weka-operator-system.svc.cluster.local:60002

  # Template type
  template: dynamic

  # Cluster topology
  dynamicTemplate:
    # Drive containers
    driveContainers: 6
    driveCores: 4
    containerCapacity: 8000  # 8TB per drive container (enables drive sharing)

    # Compute containers
    computeContainers: 6
    computeCores: 3

  # Node selection
  nodeSelector:
    weka.io/supports-backends: "true"

  # Network configuration
  network:
    deviceSubnets:
    - 10.100.0.0/16

  # Port allocation
  ports:
    basePort: 15000

  # Storage configuration
  redundancyLevel: 2
  stripeWidth: 3
  hotSpare: 1