# Drive sharing with driveCapacity + numDrives (TLC ONLY mode)
#
# This mode allocates ONLY TLC drives with fixed capacity per virtual drive.
# Each virtual drive gets exactly 1000 GiB.
#
# Use this when:
# - You want TLC-only with uniform drive sizes
# - Simple, predictable capacity allocation
# - Total capacity = numDrives × driveCapacity per container
#
# Important: This mode CANNOT use QLC drives. For mixed TLC/QLC or QLC-only,
# use containerCapacity with driveTypesRatio instead (see 02 or 04 examples)

apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: fixed-capacity-cluster
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:WEKA_VERSION
  imagePullSecret: quay-io-secret
  driversDistService: https://weka-drivers-dist.weka-operator-system.svc.cluster.local:60002
  template: dynamic

  dynamicTemplate:
    # Drive configuration with fixed capacity per drive
    driveContainers: 6
    driveCores: 4
    numDrives: 6            # Number of virtual drives per container
    driveCapacity: 1000     # 1000 GiB per drive (enables drive sharing)
    # Total per container: 6 drives × 1000 GiB = 6000 GiB

    # Compute configuration
    computeContainers: 6
    computeCores: 3

  nodeSelector:
    weka.io/supports-backends: "true"

  network:
    deviceSubnets:
    - 10.100.0.0/16

  ports:
    basePort: 15000