# Drive sharing using containerCapacity with CLUSTER-SPECIFIC driveTypesRatio override
#
# This example uses containerCapacity WITH an explicit driveTypesRatio.
# This overrides the global default from Helm values for this specific cluster.
#
# Use this when:
# - You want a different TLC/QLC ratio than the global default
# - Different clusters need different performance/cost balances
#
# For TLC-only with containerCapacity, set: driveTypesRatio: {tlc: 1, qlc: 0}
#
# Prerequisites:
# - Physical drives must have type metadata (TLC or QLC)
# - Both drive types must have sufficient capacity available (if both are used)

apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: mixed-type-cluster
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:WEKA_VERSION
  imagePullSecret: quay-io-secret
  driversDistService: https://weka-drivers-dist.weka-operator-system.svc.cluster.local:60002
  template: dynamic

  dynamicTemplate:
    # Drive configuration with type ratio
    driveContainers: 6
    driveCores: 6
    containerCapacity: 12000  # 12TB total per container
    driveTypesRatio:
      tlc: 4  # 80% TLC (high-performance)
      qlc: 1  # 20% QLC (cost-optimized)
    # Result:
    #   TLC capacity: 12000 × 4/5 = 9600 GiB (from TLC physical drives)
    #   QLC capacity: 12000 × 1/5 = 2400 GiB (from QLC physical drives)

    # Compute configuration
    computeContainers: 6
    computeCores: 3

  nodeSelector:
    weka.io/supports-backends: "true"

  network:
    deviceSubnets:
    - 10.100.0.0/16

  ports:
    basePort: 15000