# Multiple clusters sharing the same physical drives on Kubernetes nodes
# Demonstrates how to run production and development clusters side-by-side
#
# Prerequisites:
# - Drives signed for proxy mode (shared: true)
# - Sufficient total capacity: (6000 + 3000) × 6 containers = 54TB minimum
# - Each cluster uses different port ranges to avoid conflicts
#
# What happens:
# - Single proxy container per node manages physical drives
# - Each cluster allocates its own virtual drives from shared capacity
# - Virtual drive claims tracked in node annotations

---
# Production Cluster - Higher capacity and resources
apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: prod-cluster
  namespace: production
spec:
  image: quay.io/weka.io/weka-in-container:WEKA_VERSION
  imagePullSecret: quay-io-secret
  driversDistService: https://weka-drivers-dist.weka-operator-system.svc.cluster.local:60002
  template: dynamic

  dynamicTemplate:
    # Production resources
    driveContainers: 6
    driveCores: 4
    containerCapacity: 6000  # 6TB per container

    computeContainers: 6
    computeCores: 4

  nodeSelector:
    weka.io/supports-backends: "true"

  network:
    deviceSubnets:
    - 10.100.0.0/16

  ports:
    basePort: 15000  # Port range: 15000-15500

  redundancyLevel: 2
  stripeWidth: 3
  hotSpare: 1
  gracefulDestroyDuration: 5m

---
# Development Cluster - Lower capacity and resources
apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: dev-cluster
  namespace: development
spec:
  image: quay.io/weka.io/weka-in-container:WEKA_VERSION
  imagePullSecret: quay-io-secret
  driversDistService: https://weka-drivers-dist.weka-operator-system.svc.cluster.local:60002
  template: dynamic

  dynamicTemplate:
    # Development resources (smaller)
    driveContainers: 6
    driveCores: 2
    containerCapacity: 3000  # 3TB per container

    computeContainers: 6
    computeCores: 2

  nodeSelector:
    weka.io/supports-backends: "true"

  network:
    deviceSubnets:
    - 10.100.0.0/16

  ports:
    basePort: 15500  # Port range: 15500-16000 (no overlap with prod)

  redundancyLevel: 2
  stripeWidth: 3
  hotSpare: 0  # No hot spare for dev
  gracefulDestroyDuration: 0s  # Fast deletion for dev