apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pause-daemonset
  labels:
    app: pause
spec:
  selector:
    matchLabels:
      name: pause-pod
  template:
    metadata:
      labels:
        name: pause-pod
    spec:
      containers:
        - name: pause-container
          image:   # Example pause image; replace with the AWS image if different
          resources:
            limits:
              cpu: "0.1"
              memory: "100Mi"
          command: ["/pause"]
      tolerations:
        # This toleration is to ensure the daemon set pods are scheduled on the master nodes as well
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
          operator: Exists
