apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: singlecontainertest
spec:
  agentPort: 40000
  nodeSelector:
    weka.io/role: backend
  image: quay.io/weka.io/weka-in-container:4.2.10-k8so.0
  imagePullSecret: "quay-io-robot-secret"
  mode: "compute"
  name: manualcompute
  cpuPolicy: dedicated_ht
  numCores: 1
  hugepages: 3000
  port: 40001
  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  network:
    udpMode: true
