apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-dev
  namespace: default
spec:
  size: 1
  template: small
  imagePullSecret: "quay-io-robot-secret"
  topology: aws_i3en6x_udp_bless # to be removed in the future towards true discovery
  image: quay.io/weka.io/weka-in-container:4.3.3-preview.0
  driversDistService: "https://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  tolerations:
    - simple-toleration
  rawTolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "weka-backend"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "weka-backend"
      effect: "NoExecute"
  additionalMemory:
    drive: 1111
    compute: 222
    s3: 333
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaClient
metadata:
  name: cluster-dev-clients
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:4.3.3-preview.0
  imagePullSecret: "quay-io-robot-secret"
  driversDistService: "https://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  port: 45001
  agentPort: 45000
  wekaSecretRef: weka-cluster-cluster-dev
  nodeSelector:
    node.kubernetes.io/instance-type: k3s
  targetCluster:
    name: cluster-dev
    namespace: default
  coresNum: 1
  tolerations:
    - simple
    - another-simple
  rawTolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "weka-backend"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "weka-backend"
      effect: "NoExecute"
  additionalMemory: 127
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
  labels:
    app: weka-driver-builder
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.3.3-preview.0
  imagePullSecret: "quay-io-robot-secret"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002
---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
    - name: weka-driver-builder
      port: 60002
      targetPort: 60002
  selector:
    app: weka-driver-builder
