apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-dev
  namespace: default
spec:
  size: 1
  template: dynamic
  dynamicTemplate:
    computeContainers: 6
    driveContainers: 6
  imagePullSecret: "quay-io-robot-secret"
  image: quay.io/weka.io/weka-in-container:4.4.1.2766-db9740cc0982aadf1e3da5b16461d650-dev
  driversDistService: "https://weka-driver-dist.weka-operator-system.svc.cluster.local:60002"
  nodeSelector:
    weka.io/supports-backends: "true"
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaClient
metadata:
  name: cluster-dev-clients
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:4.4.1.2766-db9740cc0982aadf1e3da5b16461d650-dev
  imagePullSecret: "quay-io-robot-secret"
  driversDistService: "https://weka-driver-dist.weka-operator-system.svc.cluster.local:60002"
  port: 45001
  agentPort: 45000
  wekaSecretRef: weka-client-cluster-dev
  targetCluster:
    name: cluster-dev
    namespace: default
  coresNum: 1
  nodeSelector:
    weka.io/supports-clients: "true"
