apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-dist
  namespace: weka-operator-system
  labels:
    app: weka-driver-dist
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.4.1.741-ad4b631246430c42e5e2fdcd78ef6d74-dev
  imagePullSecret: "quay-io-robot-secret"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.4.1.741-ad4b631246430c42e5e2fdcd78ef6d74-dev
  imagePullSecret: "quay-io-robot-secret"
  mode: "drivers-builder"
  name: dist # name of the weka container, will be removed in future towards slimmer distribution service
  numCores: 1
  uploadResultsTo: "weka-driver-dist"
  port: 60002
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-loader
  namespace: weka-operator-system
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.4.1.741-ad4b631246430c42e5e2fdcd78ef6d74-dev
  imagePullSecret: "quay-io-robot-secret"
  mode: "drivers-loader"
  name: drivers-loader
  driversDistService: "https://weka-driver-dist.weka-operator-system.svc.cluster.local:60002"
  numCores: 1
  port: 60002
---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-dist
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
    - name: weka-driver-dist
      port: 60002
      targetPort: 60002
  selector:
    app: weka-driver-dist

