apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
  labels:
    app: weka-driver-builder
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.2.7.64-s3multitenancy.3
  imagePullSecret: quay-cred
  osDistro: "cos"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002
  tolerations:
    - key: "nvidia.com/gpu"
      effect: NoSchedule
      operator: Exists
  cosBuildSpec:
    gcloudCredentialsSecret: weka-builder
---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
  - name: weka-driver-builder
    port: 60002
    targetPort: 60002
  selector:
    app: weka-driver-builder
