apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-dev
  namespace: weka-operator-system
spec:
  size: 1
  template: small
  topology: hp_2drives # to be removed in the future towards true discovery
  image: quay.io/weka.io/weka-in-container:4.3.2.4927-ceb0f6b84466d2394ffff374c712bcbb-tls
  driversDistService: "https://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  imagePullSecret: "quay-io-robot-secret"
---
  apiVersion: weka.weka.io/v1alpha1
  kind: WekaCluster
  metadata:
    name: cluster-second
    namespace: weka-operator-system
  spec:
    size: 1
    template: small
    topology: hp_2drives # to be removed in the future towards true discovery
    image: quay.io/weka.io/weka-in-container:4.3.2.4927-ceb0f6b84466d2394ffff374c712bcbb-tls
    driversDistService: "https://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
    imagePullSecret: "quay-io-robot-secret"

