apiVersion: weka.weka.io/v1alpha1
kind: WekaClient
metadata:
  name: cluster-dev-clients
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:4.3.2.4927-ceb0f6b84466d2394ffff374c712bcbb-tls
  port: 35001
  agentPort: 35000
  wekaSecretRef: weka-client-cluster-dev
  imagePullSecret: "quay-io-robot-secret"
  driversDistService: "https://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  targetCluster:
    name: cluster-dev
    namespace: weka-operator-system
  network:
    ethDevice: mlnx0
