apiVersion: weka.weka.io/v1alpha1
kind: WekaManualOperation
metadata:
  name: ensure-nics-manual-op
  namespace: default
spec:
  action: "ensure-nics"
  image: quay.io/weka.io/weka-in-container:4.4.5.118-k8s.3
  imagePullSecret: "quay-io-robot-secret"
  payload:
    ensureNICsPayload:
      type: aws
      dataNICsNumber: 2
      nodeSelector: { }

