apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-second
spec:
  size: 1
  template: small_s3
  topology: discover_oci # to be removed in the future towards true discovery
  image: quay.io/weka.io/weka-in-container:4.3.1.29791-9f57657d1fb70e71a3fb914ff7d75eee-dev
  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  imagePullSecret: "quay-io-robot-secret"