apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-dev
spec:
  size: 1
  template: small_s3
  topology: discover_oci # to be removed in the future towards true discovery
  image: quay.io/weka.io/weka-in-container:4.2.7.64-s3multitenancy.2
  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  imagePullSecret: "quay-io-robot-secret"
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
  labels:
    app: weka-driver-builder
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.2.7.64-s3multitenancy.2
  imagePullSecret: "quay-io-robot-secret"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002

---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
    - name: weka-driver-builder
      port: 60002
      targetPort: 60002
  selector:
    app: weka-driver-builder