apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: wekacontainercompute0
spec:
  agentPort: 14101
  nodeAffinity: "uba-0"
  coreIds:
    - 2
  image: quay.io/weka.io/weka-in-container:4.2.10.346-9cd1d8e0430b5b24cafd47348543d899-dev
  imagePullSecret: "quay-io-robot-secret"
  mode: "compute"
  name: wekacontainercompute0
  numCores: 1
  port: 16001
  hugepages: 2000Mi
  network:
    udpMode: true
