apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: cluster-dev
spec:
  size: 1
  template: small_s3
  topology: discover_oci # to be removed in the future towards true discovery
  image: quay.io/weka.io/weka-in-container:4.3.2.560-842278e2dca9375f84bd3784a4e7515c-dev
  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  imagePullSecret: "quay-io-robot-secret"
  tolerations:
    - "test.weka.io/some-toleration"
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
  labels:
    app: weka-driver-builder
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.3.2.560-842278e2dca9375f84bd3784a4e7515c-dev
  imagePullSecret: "quay-io-robot-secret"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002

---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
    - name: weka-driver-builder
      port: 60002
      targetPort: 60002
  selector:
    app: weka-driver-builder
---
apiVersion: weka.weka.io/v1alpha1
kind: WekaClient
metadata:
  name: cluster-dev-clients
  namespace: default
spec:
  image: quay.io/weka.io/weka-in-container:4.3.2.560-842278e2dca9375f84bd3784a4e7515c-dev
  imagePullSecret: "quay-io-robot-secret"
  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
  port: 45001
  agentPort: 45000
  wekaSecretRef: weka-client-cluster-dev
  nodeSelector:
    node.kubernetes.io/instance-type: k3s
  targetCluster:
    name: cluster-dev
    namespace: default
  coresNum: 1
  tolerations:
    - "test.weka.io/some-toleration"
#  joinIpPorts: ["10.0.1.168:16101"] # dropped as targetCluster replaces this functionality for cases its both backends and clients in same k8s cluster
