apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
  labels:
    app: weka-driver-builder
spec:
  agentPort: 60001
  image: quay.io/weka.io/weka-in-container:4.2.7.64-s3multitenancy.3
  imagePullSecret: "quay-io-robot-secret"
  buildkitImagePullSecret: "ocp-buildkit-secret"
  # this is the buildkit image that will be used to build the weka driver. The image may be obtained by running the following command:
  # oc adm release info 4.13.41 --image-for=driver-toolkit. The URL may be replaced with a local mirror for a darik sites
  buildkitImage: "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2421e498039bc6118e902cef9531af6c90a3cacbe51ecb4efd37476c25caadad"
  mode: "dist"
  name: dist
  numCores: 1
  port: 60002

---
apiVersion: v1
kind: Service
metadata:
  name: weka-driver-builder
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
  - name: weka-driver-builder
    port: 60002
    targetPort: 60002
  selector:
    app: weka-driver-builder
#---
#apiVersion: weka.weka.io/v1alpha1
#kind: WekaContainer
#metadata:
#  name: weka-test-container
#  namespace: default
#spec:
#  agentPort: 50001
#  nodeSelector:
#    weka.io/role: backend
#  image: quay.io/weka.io/weka-in-container:4.2.10.621-649ace549fc60a95a4c169caf364392f-ubuntu22
#  mode: "compute"
#  name: compute
#  coreIds:
#    - 2
#  numCores: 1
#  port: 55001
#  driversDistService: "http://weka-driver-builder.weka-operator-system.svc.cluster.local:60002"
