apiVersion: weka.weka.io/v1alpha1
kind: WekaPolicy
metadata:
  name: discover-drives-policy
  namespace: weka-operator-system
spec:
  type: "discover-drives"
  image: quay.io/weka.io/weka-in-container:4.3.3.129-k8s.1-upgrade
  imagePullSecret: "quay-io-robot-secret"
  payload:
    discoverDrivesPayload:
      nodeSelector: { }
    interval: 10m
