---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: weka-operator
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 5000
    hostPort: 5000
    listenAddress: "0.0.0.0"
    protocol: TCP