#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Usage: ./script/bliss <subcommand> [args]
# Subcommands:
#   - create: Create an empty k8s cluster in AWS
#     ex: `./script/bliss create --name my-cluster --machine-template aws_small --config-file config.json`
#   - destroy: Destroy the k8s cluster in AWS
#

# Defaults
REINSTALL=""
export GOPRIVATE="github.com/weka"

while [[ $# -gt 0 ]]; do
  case "$1" in
  create)
    CMD=create
    shift
    ;;
  destroy)
    CMD=destroy
    shift
    ;;
  info)
    CMD=info
    shift
    ;;
  -n | --name)
    CLUSTER_NAME=$2
    shift 2
    ;;
  -k | --key-pair-name)
    KEY_PAIR_NAME=$2
    shift 2
    ;;
  -u | --quay-username)
    QUAY_USERNAME=$2
    shift 2
    ;;
  -p | --quay-password)
    QUAY_PASSWORD=$2
    shift 2
    ;;
  --reinstall)
    REINSTALL="--reinstall"
    shift
    ;;
  --machine-template)
    MACHINE_TEMPLATE=$2
    shift 2
    ;;
  --config-file)
    CONFIG_FILE=$2
    shift 2
    ;;
  --operator-version)
    OPERATOR_VERSION=$2
    shift 2
    ;;
  --)
    shift
    break
    ;;
  *)
    echo "Unknown argument: $1"
    exit 1
    ;;
  esac
done

if [[ -z "${CMD:-}" ]]; then
  echo "Please provide a subcommand: create or destroy"
  exit 1
fi

if [[ -z "${AWS_PROFILE:-}" ]]; then
  echo "Script should use the devkube profile"
  exit 1
fi

K=$(which kubectl)

function create() {
  echo "Creating k8s cluster in AWS"

  if [[ -z "${CLUSTER_NAME:-}" ]]; then
    echo "Please provide a cluster name"
    exit 1
  fi

  # Provision
  ## Verify cluster does not already exist
  (
    set +e
    go run github.com/weka/bliss@latest info --cluster-name "${CLUSTER_NAME}" >/dev/null 2>&1

    if [[ $? -ne 0 ]]; then
      echo "Provisioning cluster"

      args=(
        --cluster-name "${CLUSTER_NAME}"
      )

      if [[ -n "${MACHINE_TEMPLATE:-}" ]]; then
        args+=(--template "${MACHINE_TEMPLATE}")
      fi

      if [[ -n "${SUBNET_ID:-}" ]]; then
        args+=(--subnet-id "${SUBNET_ID}")
      fi

      if [[ -n "${REGION:-}" ]]; then
        args+=(--region "${REGION}")
      fi

      if [[ -n "${SECURITY_GROUP_ID:-}" ]]; then
        args+=(--security-groups "${SECURITY_GROUP_ID}")
      fi

      if [[ -n "${AMI_ID:-}" ]]; then
        args+=(--ami-id "${AMI_ID}")
      fi

      if [[ -n "${KEY_PAIR_NAME:-}" ]]; then
        args+=(--key-pair-name "${KEY_PAIR_NAME}")
      fi

      if [[ -n "${CONFIG_FILE:-}" ]]; then
        args+=(--config-file "${CONFIG_FILE}")
      fi

      go run github.com/weka/bliss@latest provision "${args[@]}"
    else
      echo "Cluster already exists"
    fi
  )

  # Scale up to 6 nodes (5 backend + 1 builder)
  CURRENT_SIZE=$(
    LOG_LEVEL=2 go run github.com/weka/bliss@latest info --cluster-name "${CLUSTER_NAME}" --json | jq -r '.node_groups[]|.instances|length'
  )
  if [[ "${CURRENT_SIZE}" -ne 6 ]]; then
    echo "Scaling up to 6 nodes"
    go run github.com/weka/bliss@latest expand \
      --cluster-name "${CLUSTER_NAME}" --size 6 --node-group-name Backends
  else
    echo "Cluster already has 6 nodes"
  fi

  # Install K8s
  echo "Installing k8s"

  INSTALL_JSON=$(
    LOG_LEVEL=2 go run github.com/weka/bliss@latest install \
      --cluster-name "${CLUSTER_NAME}" \
      --quay-username="${QUAY_USERNAME}" \
      --quay-password="${QUAY_PASSWORD}" \
      --weka-image="${WEKA_IMAGE}" \
      --no-csi \
      --no-operator \
      --no-weka-cluster \
      "{$REINSTALL}" \
      --json
  )

  #--no-weka-cluster \
  #--no-csi \
  #--no-operator \
  KUBECONFIG=$(jq -r '.kube_config_path' <<<"${INSTALL_JSON}")
  echo "KUBECONFIG: ${KUBECONFIG}"
  export KUBECONFIG

  # Label nodes
  echo "Labeling nodes"
  ## Builder Node
  BUILDER_NODE=$(${K} get node -o json | jq -r '.items[0].metadata.name')
  ${K} label node "${BUILDER_NODE}" weka.io/role=builder
  ## Backend Nodes
  ${K} label node --selector=weka.io/role!=builder weka.io/role=backend

  echo "Make sure you \`export KUBECONFIG=${KUBECONFIG}\`"
}

function destroy() {
  echo "Destroying k8s cluster in AWS"
  go run github.com/weka/bliss@latest delete "${CLUSTER_NAME}"
}

# Get cluster info
# Usage: ./script/bliss info
#
# If $CLUSTER_NAME is set, it will be passed to the info command with
# `--cluster-name`
function info() {
  ARGS=()
  if [[ -n "${CLUSTER_NAME:-}" ]]; then
    ARGS=(--cluster-name "${CLUSTER_NAME}")
  fi
  ARGS+=("$@")
  go run github.com/weka/bliss@latest info "${ARGS[@]:-}"
}

$CMD "$@"
