#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Usage: ./script/bliss <subcommand> [args]
# Subcommands:
#   - create: Create an empty k8s cluster in AWS
#   - destroy: Destroy the k8s cluster in AWS

# Defaults
REINSTALL=""
export GOPRIVATE="github.com/weka"

while [[ $# -gt 0 ]]; do
  case "$1" in
    create)
      CMD=create
      shift
      ;;
    destroy)
      CMD=destroy
      shift
      ;;
    info)
      CMD=info
      shift
      ;;
    -n | --name)
      CLUSTER_NAME=$2
      shift 2
      ;;
    -k | --key-pair-name)
      KEY_PAIR_NAME=$2
      shift 2
      ;;
    -u | --quay-username)
      QUAY_USERNAME=$2
      shift 2
      ;;
    -p | --quay-password)
      QUAY_PASSWORD=$2
      shift 2
      ;;
    --reinstall)
      REINSTALL="--reinstall"
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [[ -z "${CMD:-}" ]]; then
  echo "Please provide a subcommand: create or destroy"
  exit 1
fi

if [[ -z "${AWS_PROFILE:-}" ]]; then
  echo "Script should use the devkube profile"
  exit 1
fi

K=$(which kubectl)

function create() {
  echo "Creating k8s cluster in AWS"

  if [[ -z "${CLUSTER_NAME:-}" ]]; then
    echo "Please provide a cluster name"
    exit 1
  fi

  if [[ -z "${KEY_PAIR_NAME:-}" ]]; then
    echo "Please provide a key pair name"
    exit 1
  fi

  if [[ -z "${QUAY_USERNAME:-}" ]]; then
    echo "Please provide a Quay username"
    exit 1
  fi

  if [[ -z "${QUAY_PASSWORD:-}" ]]; then
    echo "Please provide a Quay password"
    exit 1
  fi

  # Provision
  ## Verify cluster does not already exist
  (
    set +e
    go run github.com/weka/jobless@v1.5.0 info --cluster-name "${CLUSTER_NAME}" >/dev/null 2>&1

    if [[ $? -ne 0 ]]; then
      echo "Provisioning cluster"
      go run github.com/weka/jobless@v1.5.0 provision \
        --template aws_small \
        --subnet-id subnet-0f150b5aaadcd8505 \
        --region eu-west-1 \
        --security-groups sg-03b539095aedf3ab9 \
        --ami-id ami-027429546b1b42b5a \
        --key-pair-name "${KEY_PAIR_NAME}" \
        --cluster-name "${CLUSTER_NAME}"
    else
      echo "Cluster already exists"
    fi
  )

  # Scale up to 6 nodes (5 backend + 1 builder)
  CURRENT_SIZE=$(
    LOG_LEVEL=2 go run github.com/weka/jobless@v1.5.0 info --cluster-name "${CLUSTER_NAME}" --json | jq -r '.instances|length'
  )
  if [[ "${CURRENT_SIZE}" -ne 6 ]]; then
    echo "Scaling up to 6 nodes"
    go run github.com/weka/jobless@v1.5.0 expand \
      --cluster-name "${CLUSTER_NAME}" --size 6 --node-group-name Backends
  else
    echo "Cluster already has 6 nodes"
  fi

  # Install K8s
  echo "Installing k8s"

  INSTALL_JSON=$(
    LOG_LEVEL=2 go run github.com/weka/jobless@v1.5.0 install \
      --cluster-name "${CLUSTER_NAME}" \
      --no-weka-cluster \
      --no-csi \
      --skip-operator \
      --quay-username="${QUAY_USERNAME}" \
      --quay-password="${QUAY_PASSWORD}" \
      "{$REINSTALL}" \
      --json
  )
  KUBECONFIG=$(jq -r '.kube_config_path' <<<"${INSTALL_JSON}")
  echo "KUBECONFIG: ${KUBECONFIG}"
  export KUBECONFIG

  # Label nodes
  echo "Labeling nodes"
  ## Builder Node
  BUILDER_NODE=$(${K} get node -o json | jq -r '.items[0].metadata.name')
  ${K} label node "${BUILDER_NODE}" weka.io/role=builder
  ## Backend Nodes
  ${K} label node --selector=weka.io/role!=builder weka.io/role=backend

  echo "Make sure you \`export KUBECONFIG=${KUBECONFIG}\`"
}

function destroy() {
  echo "Destroying k8s cluster in AWS"
  go run github.com/weka/jobless@v1.5.0 delete "${CLUSTER_NAME}"
}

# Get cluster info
# Usage: ./script/bliss info
#
# If $CLUSTER_NAME is set, it will be passed to the info command with
# `--cluster-name`
function info() {
  ARGS=()
  if [[ -n "${CLUSTER_NAME:-}" ]]; then
    ARGS=(--cluster-name "${CLUSTER_NAME}")
  fi
  ARGS+=("$@")
  go run github.com/weka/jobless@v1.5.0 info "${ARGS[@]:-}"
}

$CMD "$@"
