#!/bin/bash

# Script to organize PR hooks and create consolidated hook scripts
# Usage: ./organize_pr_hooks.sh <source_directory> <target_directory>

set -e

SOURCE_DIR="${1:-./test_artifacts}"
TARGET_DIR="${2:-./organized_hooks}"

echo "Organizing PR hooks from $SOURCE_DIR to $TARGET_DIR..."

# Create target directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Find all pr_XXX directories
PR_DIRS=$(find "$SOURCE_DIR" -maxdepth 1 -type d -name "pr_*")

# Check if we found any PR directories
if [ -z "$PR_DIRS" ]; then
  echo "No PR directories found in $SOURCE_DIR"
  exit 0
fi

# Organize hooks by type
for PR_DIR in $PR_DIRS; do
  PR_NAME=$(basename "$PR_DIR")
  
  echo "Processing $PR_NAME..."
  
  # Check if hooks directory exists
  HOOKS_DIR="$PR_DIR/hooks"
  if [ ! -d "$HOOKS_DIR" ]; then
    echo "No hooks directory found in $PR_NAME, skipping"
    continue
  fi
  
  # Find all hook directories
  HOOK_DIRS=$(find "$HOOKS_DIR" -mindepth 1 -maxdepth 1 -type d)
  
  for HOOK_DIR in $HOOK_DIRS; do
    HOOK_NAME=$(basename "$HOOK_DIR")
    
    echo "  Found hook: $HOOK_NAME"
    
    # Create target hook directory and PR subdirectory
    TARGET_HOOK_DIR="$TARGET_DIR/$HOOK_NAME"
    TARGET_PR_DIR="$TARGET_HOOK_DIR/$PR_NAME"
    mkdir -p "$TARGET_PR_DIR"
    
    # Copy hook files
    if [ -f "$HOOK_DIR/hook.sh" ]; then
      cp "$HOOK_DIR/hook.sh" "$TARGET_PR_DIR/"
      chmod +x "$TARGET_PR_DIR/hook.sh"
    else
      echo "    Warning: hook.sh not found in $HOOK_NAME for $PR_NAME"
    fi
    
    if [ -f "$HOOK_DIR/plan.txt" ]; then
      cp "$HOOK_DIR/plan.txt" "$TARGET_PR_DIR/"
    fi
  done
done

# Create all_prs_hook.sh for each hook type
for HOOK_TYPE_DIR in "$TARGET_DIR"/*; do
  if [ ! -d "$HOOK_TYPE_DIR" ]; then
    continue
  fi
  
  HOOK_TYPE=$(basename "$HOOK_TYPE_DIR")
  echo "Creating combined hook script for $HOOK_TYPE..."
  
  ALL_HOOKS_SCRIPT="$HOOK_TYPE_DIR/all_prs_hook.sh"
  
  # Create the combined hook script
  cat > "$ALL_HOOKS_SCRIPT" << 'EOL'
#!/bin/bash

# Combined hook script for all PRs
# Auto-generated by organize_pr_hooks.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Running all hooks for $(basename "$SCRIPT_DIR")..."

EOL
  
  # Add execution of individual PR hooks in order
  for PR_HOOK_DIR in "$HOOK_TYPE_DIR"/pr_*; do
    if [ ! -d "$PR_HOOK_DIR" ]; then
      continue
    fi
    
    PR_NAME=$(basename "$PR_HOOK_DIR")
    
    if [ -f "$PR_HOOK_DIR/hook.sh" ]; then
      cat >> "$ALL_HOOKS_SCRIPT" << EOL
echo "Running hook for $PR_NAME..."
current_dir=\$(pwd)
cd "\$SCRIPT_DIR/$PR_NAME/"
./hook.sh
if [ $? -ne 0 ]; then
  echo "Error running hook for $PR_NAME"
  exit 1
fi
cd "\$current_dir"
echo "Completed hook for $PR_NAME"
echo

EOL
    fi
  done
  
  # Make the combined script executable
  chmod +x "$ALL_HOOKS_SCRIPT"
  echo "Created $ALL_HOOKS_SCRIPT"
done

echo "Hook organization completed successfully!"
