name: CRDs Generation Check

on:
  pull_request:
  
jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@main
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}
          
  pre-commit:
    runs-on: ubuntu-latest
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21.3"
    - uses: pre-commit/action@v3.0.0
