---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/part-of: weka-operator
  {{- if .Values.aws.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
  {{- end }}
  name: "{{ .Values.prefix }}-controller-manager"
