# WekaCluster with S3
apiVersion: weka.weka.io/v1alpha1
kind: WekaCluster
metadata:
  name: my-cluster
spec:
  template: "dynamic"
  image: "quay.io/weka.io/weka-in-container:<weka-version>"
  imagePullSecret: "quay-io-robot-secret"
  driversDistService: "https://drivers.weka.io"
  dynamicTemplate:
    computeContainers: 6
    driveContainers: 6
    numDrives: 1
    s3Containers: 2
  nodeSelector:
    weka.io/role: backend
  roleNodeSelector:
    s3:
      weka.io/s3-mode: "true"
  network:
    deviceSubnets:
      - "10.0.0.0/16"
  # s3:
  #   # Additional arguments to pass to the S3 cluster create command
  #   # These are appended as-is to the weka s3 cluster create command
  #   # Useful for settings such as envoy limits
  #   clusterCreateArgs:
  #     - "--envoy-max-requests"
  #     - "1150"
  #     - "--envoy-max-connections"
  #     - "1300"
  #     - "--envoy-max-pending-requests"
  #     - "1450"
