package condition

const (
	CondPodsCreated                  = "PodsCreated"
	CondClusterSecretsCreated        = "ClusterSecretsCreated"
	CondClusterSecretsApplied        = "ClusterSecretsApplied"
	CondAdminUserDeleted             = "CondAdminUserDeleted"
	CondClusterClientSecretsCreated  = "ClusterClientsSecretsCreated"
	CondClusterClientSecretsApplied  = "ClusterClientsSecretsApplied"
	CondClusterCSISecretsCreated     = "ClusterCSIsSecretsCreated"
	WekaHomeConfigured               = "WekaHomeConfigured"
	CondClusterCSISecretsApplied     = "ClusterCSIsSecretsApplied"
	CondDefaultFsCreated             = "CondDefaultFsCreated"
	CondS3ClusterCreated             = "CondS3ClusterCreated" // not pre-set on purpose, as optional
	ConfNfsConfigured                = "NfsConfigured"
	CondNfsInterfaceGroupsConfigured = "NfsInterfaceGroupsConfigured"
	CondPodsReady                    = "PodsReady"
	CondClusterCreated               = "ClusterCreated"
	CondJoinIpsSet                   = "JoinIpsSet"
	CondDrivesAdded                  = "DrivesAdded"
	CondIoStarted                    = "IoStarted"
	CondJoinedCluster                = "JoinedCluster"
	CondJoinedS3Cluster              = "JoinedS3Cluster"
	CondContainerResourcesWritten    = "ContainerResourcesWritten"
	CondResultsReceived              = "CondResultsReceived"
	CondResultsProcessed             = "CondResultsProcessed"
	CondEnsureDrivers                = "EnsuredDrivers"
	CondContainerResourcesAllocated  = "ContainerResourcesAllocated"
	CondContainerDeactivated         = "ContainerDeactivated"
	CondContainerDrivesDeactivated   = "ContainerDrivesDeactivated"
	CondContainerRemoved             = "ContainerRemoved"
	CondContainerDrivesResigned      = "ContainerDrivesResigned"
	CondContainerDrivesRemoved       = "ContainerDrivesRemoved"
	CondContainerAffinitySet         = "ContainerAffinitySet"
	CondClusterReady                 = "ClusterIsReady"
)
